serve:
  name:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
    show-sql:
    properties:
      hibernate:
        format_sql:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name:
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type:
            scope:
        provider:
          naver:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute:

swagger:
  enabled:

springdoc:
  api-docs:
    path:
  default-consumes-media-type:
  default-produces-media-type:
  version:
  swagger-ui:
    path:
    defaultModelsExpandDepth:
    default-model-expand-depth:

clova:
  hcx007:
    url:
    key:

jwt:
  secret:
  access-token-expiration:
  refresh-token-expiration: