server:
  name: Quizly

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 50MB # 파일 하나의 최대 크기
      maxRequestSize: 50MB  # 한 번에 최대 업로드 가능 용량
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

swagger:
  enabled: true

springdoc:
  api-docs:
    path: ${SPRING_PATH}
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  version: 0.1
  swagger-ui:
    path: ${SWAGGER_PATH}
    defaultModelsExpandDepth: 3
    default-model-expand-depth: 3

clova:
  hcx007:
    url: https://clovastudio.stream.ntruss.com/v3/chat-completions/HCX-007
    key: ${CLOVA_KEY}

ocr:
  api:
    url: https://l3vgawapd7.apigw.ntruss.com/custom/v1/45109/102c2f4dc7f9cfc6c16118f779239c1f9a3431cd033686ef7370c17cc1606dd3/general
    secret: ${OCR_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

object-storage:
  bucket: ${OBJECT_BUCKET}
  endpoint: https://kr.object.ncloudstorage.com
  region: ap-northeast-2
  credentials:
    access-key: ${NCP_OBJECT_ACCESS_KEY}
    secret-key: ${NCP_OBJECT_SECRET_KEY}

custom:
  oauth2:
    front-redirect-url: ${FRONT_REDIRECT_URL}