name: Quizly Deploy (NCP)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML_PROD }}" > ./src/main/resources/application.yml

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Transfer Config to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST_PROD }}
          username: ${{ secrets.NCP_USERNAME_PROD }}
          password: ${{ secrets.NCP_PASSWORD_PROD }}
          port: ${{ secrets.NCP_PORT_PROD }}
          source: "./src/main/resources/application.yml"
          target: "/root/quizly-server"
          strip_components: 4

      - name: Transfer Script to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST_PROD }}
          username: ${{ secrets.NCP_USERNAME_PROD }}
          password: ${{ secrets.NCP_PASSWORD_PROD }}
          port: ${{ secrets.NCP_PORT_PROD }}
          source: "./deploy-prod.sh"
          target: "/root/quizly-server"

      - name: Build & Push to NCR
        run: |
          echo "Logging into NCR..."
          docker login ${{ secrets.NCP_CONTAINER_REGISTRY }} -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }}
          
          echo "Building Image..."
          docker build -t ${{ secrets.NCP_CONTAINER_REGISTRY }}/quizly:${{ github.sha }} .
          
          echo "Pushing Image..."
          docker push ${{ secrets.NCP_CONTAINER_REGISTRY }}/quizly:${{ github.sha }}

      - name: Execute Deploy Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST_PROD }}
          username: ${{ secrets.NCP_USERNAME_PROD }}
          password: ${{ secrets.NCP_PASSWORD_PROD }}
          port: ${{ secrets.NCP_PORT_PROD }}
          script: |
            docker login ${{ secrets.NCP_CONTAINER_REGISTRY }} -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }}
            cd /root/quizly-server
            chmod +x deploy-prod.sh
            ./deploy-prod.sh ${{ secrets.NCP_CONTAINER_REGISTRY }}/quizly ${{ github.sha }}